### PR TITLE
ACodec: 64bit VideoNativeMetadata enablement

### PR DESCRIPTION
**Pull request by fredldotme**
This change set includes:

- A prerequisite for both OMX and C2 devices to make use of native window buffers in 64bit processes
- Actually use those _ptrSized structs in ACode to allow passing native window buffers to the 32bit OMX process

Prerequisite for the encoder within Aethercast/Wireless Display Support on Halium 9.0

### CODE REVIEW

**Comment by peat-psuwit** [comment]
So mer-hybris _does_ ship these patches, right? I have a conversation with @NotKit some time ago and he doesn't actually sure that they shipped them.

Also, maybe rebase to remove intermediary commits?

**Comment by fredldotme** [comment]
> So mer-hybris _does_ ship these patches, right? I have a conversation with @NotKit some time ago and he doesn't actually sure that they shipped them.

If they don't then there is no way in hell Droidmedia would be able to pass buffers between it and 32bit OMX... ;)

**Comment by fredldotme** [comment]
Btw, can't we just squash this PR into one commit and call it a day?

**Comment by peat-psuwit** [comment]
> Btw, can't we just squash this PR into one commit and call it a day?

Your choice.

**Comment by fredldotme** [comment]
> > Btw, can't we just squash this PR into one commit and call it a day?
> 
> Your choice.

https://www.youtube.com/watch?v=5jKZ9KGtee0

Or in other words: yes please :P

**Comment by peat-psuwit** [comment]
Note: this will also enable video recording through gst-droid.

**Comment by peat-psuwit** [comment]
For QA: on exactly Android 9 devices (not including Android 10 or newer), make sure that video playback & video recording on camera doesn't break.

**Pull request merged**
