### PR TITLE
hybris-patches: Add back mkimage

### PR DESCRIPTION
**Pull request by Herrie82**
mkimage is needed for building HP Touchpad (tenderloin) Halium images.

Seems mkimage was removed from LineageOS 16.0. Adding back the version that was available up to LineageOS 15.1.

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by Tofee** [comment]
LGTM. Maybe we should just check that it builds fine on aarch64.

**Comment by Herrie82** [comment]
> LGTM. Maybe we should just check that it builds fine on aarch64.

Tested with Tissot (aarch64) and it builds OK.

**Comment by fredldotme** [comment]
Are you sure it has been tested well enough? The diff header was missing the line adjustment as the patch seems to have been modified by hand instead of amended. This broke builds on our side, since the embedded.mk wasn't included anymore.

**Comment by Herrie82** [comment]
> Are you sure it has been tested well enough? The diff header was missing the line adjustment as the patch seems to have been modified by hand instead of amended. This broke builds on our side, since the embedded.mk wasn't included anymore.

Weird, I tested it cleanly here on 2 targets. Let me double check and push a fix if needed.

**Comment by fredldotme** [comment]
Make sure it includes the last line of the patch that you modified in your testing, the embedded.mk. If that's missing in the resulting file it needs changes.

**Comment by Herrie82** [comment]
> Make sure it includes the last line of the patch that you modified in your testing, the embedded.mk. If that's missing in the resulting file it needs changes.

This should fix it. Sorry for the oversight: https://github.com/Halium/hybris-patches/commit/a9ab53bcf9a2901e796eacacbded014ffad2781e

**Pull request merged**
