### PR TITLE
(halium) build/make: avoid python mismatch by explicitly use python2

### PR DESCRIPTION
**Pull request by Vince1171**
Change-Id: I5ce8d146c08efadb2f7ded33612d6018ff9fe238

### CODE REVIEW

**Comment by Vince1171** [comment]
this allow to compile Halium whether `python` is `python2` or `python3`
(and prevent issue as `repo` now use assume `python` is `python3`)

**Comment by fredldotme** [comment]
Looks good, I've tested this locally now in an Ubuntu 18.04 container. Will merge as soon as UT OTA-16 is out.
Please remind me if it's not merged the day after release :P

**Comment by Vince1171** [comment]
@fredldotme ;)

**Comment by fredldotme** [comment]
Let's see if this breaks anything.

**Pull request merged**
